const mongoose = require('mongoose')
const schema = new mongoose.Schema(
  {
    aliasName: {type:String},
    attachUserId:{type:Number},
    auth: {type:Number},
    avatar: {type:String},
    bgImg: {type:String},
    birthday: {type:String},
    birthplace: {type:String},
    bloodType: {type:String},
    boardUrl: {type:String},
    cnm: {type:String},
    company: {type:String},
    constellation: {type:String},
    deathDate: {type:String},
    desc: {type:String},
    enm: {type:String},
    fansName: {type:String},
    followCount: {type:Number},
    followRank: {type:Number},
    followState: {type:Number},
    graduateSchool: {type:String},
    height: {type:Number},
    id: {type:Number},
    nation: {type:String},
    nationality: {type:String},
    photoNum: {type:Number},
    photos:[{type:String}],
    present:{type:Number},
    presentImg: {type:String},
    publicTitles: [{type:String}],
    rank: {type:Number},
    receiveWord: {type:String},
    sendWord: {type:String},
    sexy: {type:String},
    signImg: {type:String},
    still: {type:String},
    sumBox: {type:Number},
    titleList:[{type:String}],
    titles: {type:String},
    userDailyPresent: {type:Number},
    works:{
      total:{type:Number},
      movies:[{
        avatar: {type:String},
        cr: {type:Number},
        duty: {type:String},
        globalReleased: {type:Boolean},
        id: {type:Number},
        mbox: {type:Number},
        multiroles: {type:String},
        mutlidutys: {type:String},
        name: {type:String},
        order: {type:Number},
        pubDate: {type:Number},
        roles: {type:String},
        rt: {type:String},
        sc: {type:Number},
        showst: {type:Number},
        wish: {type:Number},
        wishst:{type:Number},
      }]
    }
  }
)
module.exports = mongoose.model('Celebrity', schema)  